### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by abaanshanid** [takase1121/lite-xl-immersive-title#1]
Hi, I just started using Lite XL and yeah I hate the white titlebar. So I downloaded the init.lua file and added it in a folder named immersive-title inside the plugins folder, but I still have the same light titlebar. Is there anything I'm missing?

Thanks

**Comment by takase1121** [comment]
Please follow the first instruction on the README.

**Comment by abaanshanid** [comment]
Oh crap, sorry for wasting your time and thanks for the quick reply.
